#include <stm8s.h>

// brief:
// toggle onboard LED using an external button (on PD4)


#define LED_PIN 5
#define BUTTON_PIN 4


//  Process the interrupt generated by the pressing of the button on PD4.
void EXTI_PORTD_IRQHandler() __interrupt(EXTI3_ISR)
{
  PB_ODR ^= (1 << LED_PIN); // toggle output pin
}


void main()
{
  disable_interrupts();

  // output LED
  PB_DDR |= (1 << LED_PIN);
  //PB_CR1 |= (1 << LED_PIN); //  push-pull
  PB_CR1 &= ~(1 << LED_PIN); //  open drain

  // Configure input pin as floating with interrupt:
  // DDR 0; CR1 0; CR2 1  (reference man p. 107)
  PD_DDR &= ~(1 << BUTTON_PIN);
  PD_CR1 &= ~(1 << BUTTON_PIN);
  PD_CR2 |= (1 << BUTTON_PIN);

  //  Set up the interrupt.
  EXTI_CR1 |= (1 << EXTI_CR1_PDIS1);  // Interrupt on falling edge only.
  EXTI_CR1 &= ~(1 << EXTI_CR1_PDIS0);
  EXTI_CR2 &= ~(1 << EXTI_CR2_TLIS);  // top level falling edge only.

  enable_interrupts();

  while (1)
  {
    // wait for interrupt
  }
}
