#include <stm8s.h>
#include <utils.h>
#include <delay.h>

// brief:
// measure elapsed seconds on external interrupt (button press)
// blink for number of elapsed seconds
// reset counter and measure again
// use TIM4 for both counting seconds and delay


uint32_t elapsed_s;


//  Process the interrupt generated by the pressing of the button on PD4.
void EXTI_PORTD_IRQHandler(void) __interrupt(EXTI3_ISR)
{
  if (elapsed_s == 0)
  {
    elapsed_s = read_tim4_counter() / 200000;
    reset_tim4_counter();
    //elapsed_s = 2;
  }
}


#define LED_PIN 5
#define BUTTON_PIN 4


void main() {
  elapsed_s = 2;
  disable_interrupts();
  initialize_system_clock();

  // configure LED_PIN for output
  set_bit(PB_DDR, LED_PIN);
  set_bit(PB_CR1, LED_PIN);  //  push-pull
  //clr_bit(PB_CR1, LED_PIN);  //  open drain

  // Configure input pin as floating with interrupt:
  // DDR 0; CR1 0; CR2 1  (reference man p. 107)
  PD_DDR &= ~(1 << BUTTON_PIN);
  PD_CR1 &= ~(1 << BUTTON_PIN);
  PD_CR2 |= (1 << BUTTON_PIN);

  //  Set up the interrupt.
  EXTI_CR1 |= (1 << EXTI_CR1_PDIS1);  // Interrupt on falling edge only.
  EXTI_CR1 &= ~(1 << EXTI_CR1_PDIS0);
  EXTI_CR2 &= ~(1 << EXTI_CR2_TLIS);  // top level falling edge only.

  enable_interrupts();

  while (1) {
    if (elapsed_s)
    {
      // blink for number of elapsed seconds
      //PB_ODR &= ~(1 << LED_PIN);
      clr_bit(PB_ODR, LED_PIN);
      delay_ms(300);
      //PB_ODR |= (1 << LED_PIN);
      set_bit(PB_ODR, LED_PIN);
      delay_ms(300);
      elapsed_s--;
      if (elapsed_s == 0)
      {
        // TODO disable / enable GPIO interrupt
        reset_tim4_counter();
      }
    }
  }
}
